name: dxmc

on:
  push:
    branches: [ develop ]


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install OpenSSL
      run: |
        choco install openssl  
        echo "::set-env name=INCLUDE::C:\\Program Files\\OpenSSL-Win64\\include;%INCLUDE%"
        echo "::set-env name=LIB::C:\\Program Files\\OpenSSL-Win64\\lib;%LIB%"        
        

    - name: Install dependencies
      run: |
        echo %INCLUDE%
        python -m pip install --upgrade pip
        python -m pip install cryptography
        python setup.py install
        pip install pyinstaller
        pyinstaller --onefile --clean dxmc.py
